apiVersion: v1
kind: Pod
metadata:
  name: demo-pod
  labels:
    app: demo
spec:
  containers:
    - name: demo-nginx
      image: nginx
      ports:
        - name: demo-ngnix
          containerPort: 80